DOMAIN = "heatly_test"
CONF_ROOM_ID = "room_id"
CONF_TEMP_SENSOR = "temp_sensor"
CONF_HEATER_SWITCH = "heater_switch"
CONF_HEATER_SWITCHES = "heater_switches"  # Multiple heaters support
CONF_OUTDOOR_SENSOR = "outdoor_sensor"
CONF_API_URL = "api_url"
CONF_COLD_TOLERANCE = "cold_tolerance"
CONF_HOT_TOLERANCE = "hot_tolerance"
DEFAULT_API_URL = "http://localhost:5364"
DEFAULT_COLD_TOLERANCE = 0.5  # Degrees C below target to turn on heater
DEFAULT_HOT_TOLERANCE = 0.5  # Degrees C above target to turn off heater
SCAN_INTERVAL_SECONDS = 60  # Send sensor data every 60 seconds
SCHEDULE_CACHE_SECONDS = 300  # Cache schedules for 5 minutes
MIN_SWITCH_INTERVAL_SECONDS = 60  # Minimum time between heater state changes